# Generated by Django 5.2.14 on 2026-05-26 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations', '0002_inspirationcomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inspirationcomment',
            new_name='inspiration_inspira_2037fc_idx',
            old_name='inspiratio_inspir_0654b5_idx',
        ),
        migrations.RenameIndex(
            model_name='inspirationcomment',
            new_name='inspiration_reviewe_ff27e9_idx',
            old_name='inspiratio_reviewe_4150dd_idx',
        ),
        migrations.RenameIndex(
            model_name='inspirationcomment',
            new_name='inspiration_parent__46cc29_idx',
            old_name='inspiratio_parent__aa5b0a_idx',
        ),
    ]
