# Generated by Django 5.2.14 on 2026-05-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(upload_to='artworks/%Y/%m/', verbose_name='画作图片')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('is_available', models.BooleanField(default=True, verbose_name='可购买')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '画作',
                'verbose_name_plural': '画作',
                'ordering': ['-created_at'],
            },
        ),
    ]
