# Generated by Django 5.2.14 on 2026-05-25 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_image_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['owner', '-created_at'], name='artworks_ar_owner_i_afcfa0_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category', '-created_at'], name='artworks_ar_categor_c02496_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['is_available', '-created_at'], name='artworks_ar_is_avai_ee1a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['-created_at'], name='artworks_ar_created_809d6e_idx'),
        ),
    ]
