# Generated by Django 5.2.14 on 2026-05-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
