# Generated by Django 5.2.14 on 2026-07-11 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_direct_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_direct_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["sender", "recipient", "created_at"],
                        name="users_direc_sender__5bc484_idx",
                    ),
                    models.Index(
                        fields=["recipient", "read_at", "-created_at"],
                        name="users_direc_recipie_663795_idx",
                    ),
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="users_direc_sender__d63886_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sender", models.F("recipient")),
                            _negated=True,
                        ),
                        name="users_dm_no_self",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("body", ""), _negated=True),
                        name="users_dm_body_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["from_user", "-created_at"],
                        name="users_follo_from_us_c813da_idx",
                    ),
                    models.Index(
                        fields=["to_user", "-created_at"],
                        name="users_follo_to_user_74b25b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_user", "to_user"),
                        name="users_follow_unique_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_user", models.F("to_user")),
                            _negated=True,
                        ),
                        name="users_follow_no_self",
                    ),
                ],
            },
        ),
    ]
