# Generated by Django 5.2.14 on 2026-07-17 12:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="消息内容")),
                ("is_user", models.BooleanField(default=True, verbose_name="是否用户消息")),
                (
                    "conversation_id",
                    models.UUIDField(default=uuid.uuid4, verbose_name="会话 ID"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 聊天消息",
                "verbose_name_plural": "AI 聊天消息",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "conversation_id", "-created_at"],
                        name="recommendat_user_id_5c4b77_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="recommendat_user_id_61cbc0_idx",
                    ),
                ],
            },
        ),
    ]

