# Generated by Django 5.2.16 on 2026-07-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0004_artwork_artworks_ar_owner_i_afcfa0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(default=dict, verbose_name='偏好向量')),
                ('top_categories', models.JSONField(default=list, verbose_name='偏好分类')),
                ('top_tags', models.JSONField(default=list, verbose_name='偏好标签')),
                ('price_range', models.JSONField(default=dict, verbose_name='价格区间偏好')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户推荐画像',
                'verbose_name_plural': '用户推荐画像',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', '浏览'), ('like', '点赞'), ('purchase', '购买'), ('collect', '收藏'), ('comment', '评论'), ('search', '搜索')], max_length=20, verbose_name='行为类型')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='搜索标签')),
                ('score', models.FloatField(default=1.0, verbose_name='行为得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='artworks.artwork', verbose_name='画作')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_8fea2a_idx'), models.Index(fields=['artwork', '-created_at'], name='recommendat_artwork_b71ca8_idx'), models.Index(fields=['action_type', '-created_at'], name='recommendat_action__bd19fe_idx'), models.Index(fields=['-created_at'], name='recommendat_created_c02026_idx')],
            },
        ),
    ]
