# Generated by Django 5.2.14 on 2026-05-25 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_artwork_artworks_ar_owner_i_afcfa0_idx_and_more'),
        ('orders', '0002_initial'),
        ('reviews', '0003_review_image_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['artwork', '-created_at'], name='reviews_rev_artwork_4d7b98_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', '-created_at'], name='reviews_rev_reviewe_5e332e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['target_user', '-created_at'], name='reviews_rev_target__30028c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_rev_created_03e07d_idx'),
        ),
    ]
