# Generated by Django 5.2.14 on 2026-05-13 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='定制标题')),
                ('description', models.TextField(verbose_name='需求描述')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='custom/%Y/%m/', verbose_name='参考图')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预算')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('accepted', '已接单'), ('in_progress', '创作中'), ('reviewing', '待确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='submitted', max_length=20, verbose_name='状态')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='进度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '线上定制',
                'verbose_name_plural': '线上定制',
                'ordering': ['-created_at'],
            },
        ),
    ]
