# Generated by Django 5.2.14 on 2026-05-13 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customrequest',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_jobs', to=settings.AUTH_USER_MODEL, verbose_name='接单画师'),
        ),
        migrations.AddField(
            model_name='customrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to=settings.AUTH_USER_MODEL, verbose_name='需求方'),
        ),
    ]
