# Generated by Django 5.2.14 on 2026-05-25 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_customrequest_shared_commissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customrequest',
            index=models.Index(fields=['status', '-created_at'], name='custom_cust_status_fcd9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='customrequest',
            index=models.Index(fields=['requester', '-created_at'], name='custom_cust_request_f489ae_idx'),
        ),
        migrations.AddIndex(
            model_name='customrequest',
            index=models.Index(fields=['artist', '-created_at'], name='custom_cust_artist__7ae043_idx'),
        ),
        migrations.AddIndex(
            model_name='customrequest',
            index=models.Index(fields=['-created_at'], name='custom_cust_created_8776ac_idx'),
        ),
    ]
