# Generated by Django 5.2.14 on 2026-05-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_commissionoption'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissionoption',
            new_name='custom_comm_is_acti_40c8e0_idx',
            old_name='custom_comm_is_acti_3d8e2b_idx',
        ),
    ]
