# Generated by Django 5.2.14 on 2026-07-10 15:53

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0006_rename_custom_comm_is_acti_3d8e2b_idx_custom_comm_is_acti_40c8e0_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customrequest",
            name="agreed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="成交价",
            ),
        ),
        migrations.CreateModel(
            name="CommissionBid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="报价",
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=1000, verbose_name="报价说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "竞价中"),
                            ("withdrawn", "已撤回"),
                            ("selected", "已中选"),
                            ("rejected", "未中选"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_bids",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="报价画师",
                    ),
                ),
                (
                    "custom_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="custom.customrequest",
                        verbose_name="委托",
                    ),
                ),
            ],
            options={
                "verbose_name": "委托报价",
                "verbose_name_plural": "委托报价",
                "ordering": ["amount", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="customrequest",
            name="selected_bid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_for_request",
                to="custom.commissionbid",
                verbose_name="中选报价",
            ),
        ),
        migrations.CreateModel(
            name="CommissionInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                        verbose_name="邀请报价",
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=1000, verbose_name="邀请说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待回应"),
                            ("accepted", "已接受"),
                            ("declined", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True, verbose_name="回应时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_commission_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="受邀画师",
                    ),
                ),
                (
                    "custom_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="custom.customrequest",
                        verbose_name="委托",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_commission_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="邀请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "定向邀请",
                "verbose_name_plural": "定向邀请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commissionbid",
            index=models.Index(
                fields=["custom_request", "status", "-updated_at"],
                name="custom_comm_custom__b30837_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commissionbid",
            index=models.Index(
                fields=["artist", "status", "-updated_at"],
                name="custom_comm_artist__1d7ab7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionbid",
            constraint=models.UniqueConstraint(
                fields=("custom_request", "artist"),
                name="custom_unique_bid_artist",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionbid",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "selected")),
                fields=("custom_request",),
                name="custom_one_selected_bid",
            ),
        ),
        migrations.AddIndex(
            model_name="commissioninvitation",
            index=models.Index(
                fields=["custom_request", "status", "-updated_at"],
                name="custom_comm_custom__bb9d1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commissioninvitation",
            index=models.Index(
                fields=["artist", "status", "-updated_at"],
                name="custom_comm_artist__2bbd95_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissioninvitation",
            constraint=models.UniqueConstraint(
                fields=("custom_request", "artist"),
                name="custom_unique_invite_artist",
            ),
        ),
        migrations.AddConstraint(
            model_name="commissioninvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("artist", models.F("invited_by")), _negated=True),
                name="custom_inviter_not_artist",
            ),
        ),
    ]
